"""empty message

Revision ID: 05cf0da3f324
Revises: 9370fd7e91c9
Create Date: 2023-05-15 15:13:06.125036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cf0da3f324'
down_revision = '9370fd7e91c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.alter_column('downloads',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.alter_column('downloads',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
