"""empty message

Revision ID: 170fb245f165
Revises: 2be23e903663
Create Date: 2023-05-05 00:32:00.854101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170fb245f165'
down_revision = '2be23e903663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
