"""empty message

Revision ID: 9370fd7e91c9
Revises: 170fb245f165
Create Date: 2023-05-15 15:03:16.501059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9370fd7e91c9'
down_revision = '170fb245f165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downloads', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallpaper', schema=None) as batch_op:
        batch_op.drop_column('downloads')

    # ### end Alembic commands ###
